
//Inscription
POST localhost:9084/signup
Content-Type: application/json

{
  "pseudo": "Mardino",
  "email": "maxdassi01@gmail.com",
  "password": "456321"
}
###
///Connexion
POST localhost:9084/login
Content-Type: application/json

{
"username": "maxdassi02@gmail.com",
"password": "456321"
}

###
GET http://localhost:9084/chief
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MjIzNzcwNjEsIm5vbSI6Ik1hcmRpbm8iLCJzdWIiOiJtYXhkYXNzaTAyQGdtYWlsLmNvbSJ9.u8mOes7CI4NDy3ZRZrnc-vYOCEqlb5lxuN5yjN_qdkM